---
- hosts: all
  tasks:
    - block:
        - name: Run make rpm
          shell:
            cmd: |
                make rpm
            chdir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/containers/libpod'].src_dir }}"
          changed_when: true

      rescue:
        - name: Don't block
          debug:
            msg: podman rpm build failed
