---
- hosts: primary
  tasks:
    - name: Clone repos in the job workspace
      ansible.builtin.include_role:
        name: prepare-workspace

    - name: Install copy_containers
      ansible.builtin.include_role:
        name: copy_container
        tasks_from: main
      vars:
        enable_cron: false
        enable_cron_c9: false

    - name: Create the config file
      ansible.builtin.template:
        src: "{{ playbook_dir }}/files/copy-quay-config.yaml.j2"
        dest: "{{ work_dir }}/copy-quay-config.yaml"
        mode: '0755'

    # https://bugs.launchpad.net/tripleo/+bug/1988500
    - name: Downgrade containers-common due to bug
      ansible.builtin.shell: |
        sudo dnf install -y podman
        sudo dnf config-manager --setopt 'appstream.exclude=containers-common-1-44.*' appstream --save
        sudo dnf -y downgrade containers-common-1-40.el9
