- hosts: all
  tasks:

    # to test rhel8 rhui based containers we need to be sure that we can
    # resolve rhui-cds
    - name: adds rhui-cds to /etc/hosts
      become: true
      lineinfile:
        dest: /etc/hosts
        regexp: '.*rhui-cds$'
        line: "38.145.32.241 rhui-cds"
        state: present

    # Update required to pull cryptography wheels https://github.com/pyca/cryptography/issues/5771
    - name: Update pip to latest
      become: true
      pip:
        name: pip
        state: latest
        extra_args: --upgrade

    # TODO(jcapitao): Use Zuul upstream ensure-ansible role [1] when it's
    # merged.
    # [1] https://review.opendev.org/c/zuul/zuul-jobs/+/749706
    - name: Install Ansible
      become: true
      pip:
        name: ansible
        version: "{{ ensure_ansible_version|default('latest', true) }}"
        state: "{{ ensure_ansible_state|default('present', true) }}"
